export const PRODUCT_TYPE = {
  ADD_PRODUCT_TYPE: "ADD_PRODUCT_TYPE",
  GET_PRODUCTS_TYPE: "GET_PRODUCTS_TYPE",
  LOADING_PRODUCTS_TRUE: "LOADING_PRODUCTS_TRUE",
  LOADING_PRODUCTS_FALSE: "LOADING_PRODUCTS_FALSE",
};
