export const ERROR_CODES = {
  CART_ITEMS: "CART_ITEMS",
  PAYMENT: "PAYMENT",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  VERIFI: "VERIFI",
  AUTH: "UNAUTHENTICATED",
};
